"""empty message

Revision ID: d106c2be3264
Revises: 0c2fae3d4c47
Create Date: 2022-07-25 20:12:21.792206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd106c2be3264'
down_revision = '0c2fae3d4c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('citizen', sa.Boolean(), nullable=True))

    op.execute('UPDATE users SET citizen=False WHERE citizen IS NULL')

    op.alter_column('users', 'citizen', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'citizen')
    # ### end Alembic commands ###
